package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestIsAgentSupported(t *testing.T) {
	tests := []struct {
		name      string
		agentType string
		want      bool
	}{
		{
			name:      "claude slug is supported",
			agentType: "claude",
			want:      true,
		},
		{
			name:      "claude-code alias is supported",
			agentType: "claude-code",
			want:      true,
		},
		{
			name:      "codex is supported",
			agentType: "codex",
			want:      true,
		},
		{
			name:      "cursor is not supported",
			agentType: "cursor",
			want:      false,
		},
		{
			name:      "windsurf is not supported",
			agentType: "windsurf",
			want:      false,
		},
		{
			name:      "droid is not supported",
			agentType: "droid",
			want:      false,
		},
		{
			name:      "empty agent type is not supported",
			agentType: "",
			want:      false,
		},
		{
			name:      "unknown agent is not supported",
			agentType: "unknown-agent",
			want:      false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isAgentSupported(tt.agentType)
			if got != tt.want {
				t.Errorf("isAgentSupported(%q) = %v, want %v", tt.agentType, got, tt.want)
			}
		})
	}
}

func TestGetAgentSupportNotice(t *testing.T) {
	tests := []struct {
		name         string
		agentType    string
		wantEmpty    bool
		wantContains string
	}{
		{
			name:      "claude returns empty notice",
			agentType: "claude",
			wantEmpty: true,
		},
		{
			name:      "claude-code alias returns empty notice",
			agentType: "claude-code",
			wantEmpty: true,
		},
		{
			name:      "codex returns empty notice",
			agentType: "codex",
			wantEmpty: true,
		},
		{
			name:         "cursor returns notice with display name",
			agentType:    "cursor",
			wantEmpty:    false,
			wantContains: "Cursor",
		},
		{
			name:         "empty agent returns notice about this agent",
			agentType:    "",
			wantEmpty:    false,
			wantContains: "this agent",
		},
		{
			name:         "windsurf returns notice with display name",
			agentType:    "windsurf",
			wantEmpty:    false,
			wantContains: "Windsurf",
		},
		{
			name:         "unsupported agent notice explains review needed",
			agentType:    "cursor",
			wantEmpty:    false,
			wantContains: "review plans deeply",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := getAgentSupportNotice(tt.agentType)

			if tt.wantEmpty && got != "" {
				t.Errorf("getAgentSupportNotice(%q) = %q, want empty", tt.agentType, got)
			}

			if !tt.wantEmpty && got == "" {
				t.Errorf("getAgentSupportNotice(%q) = empty, want non-empty", tt.agentType)
			}

			if tt.wantContains != "" && !strings.Contains(got, tt.wantContains) {
				t.Errorf("getAgentSupportNotice(%q) = %q, want to contain %q", tt.agentType, got, tt.wantContains)
			}
		})
	}
}

func TestLoadTeamInstructions(t *testing.T) {
	tests := []struct {
		name      string
		files     map[string]string // filename -> content
		teamName  string
		wantNil   bool
		wantFiles []string
		wantIn    string // substring expected in content
	}{
		{
			name:    "empty dir returns nil",
			files:   map[string]string{},
			wantNil: true,
		},
		{
			name: "auto-generated AGENTS.md is skipped",
			files: map[string]string{
				"AGENTS.md": "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0 at 2026-01-01T00:00:00Z*\n",
			},
			wantNil: true,
		},
		{
			name: "real AGENTS.md is loaded",
			files: map[string]string{
				"AGENTS.md": "# Team Instructions\n\nUse Go for everything.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"AGENTS.md"},
			wantIn:    "Use Go for everything",
		},
		{
			name: "CLAUDE.md only is loaded",
			files: map[string]string{
				"CLAUDE.md": "# Claude Config\n\nPrefer simplicity.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"CLAUDE.md"},
			wantIn:    "Prefer simplicity",
		},
		{
			name: "both files are concatenated",
			files: map[string]string{
				"AGENTS.md": "# Agent Instructions\n\nRule one.\n",
				"CLAUDE.md": "# Claude Config\n\nRule two.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"AGENTS.md", "CLAUDE.md"},
			wantIn:    "Rule one",
		},
		{
			name: "boilerplate AGENTS.md plus real CLAUDE.md returns only CLAUDE.md",
			files: map[string]string{
				"AGENTS.md": "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0*\n",
				"CLAUDE.md": "# Claude Config\n\nReal instructions.\n",
			},
			teamName:  "TestTeam",
			wantFiles: []string{"CLAUDE.md"},
			wantIn:    "Real instructions",
		},
		{
			name:    "empty path returns nil",
			files:   nil,
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// handle empty path case
			if tt.files == nil {
				got := loadTeamInstructions("", tt.teamName)
				if got != nil {
					t.Fatalf("loadTeamInstructions(\"\", ...) = non-nil, want nil")
				}
				return
			}

			dir := t.TempDir()
			for name, content := range tt.files {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
					t.Fatalf("write %s: %v", name, err)
				}
			}

			got := loadTeamInstructions(dir, tt.teamName)

			if tt.wantNil {
				if got != nil {
					t.Fatalf("want nil, got %+v", got)
				}
				return
			}

			if got == nil {
				t.Fatal("want non-nil, got nil")
			}

			if got.TeamName != tt.teamName {
				t.Errorf("team_name = %q, want %q", got.TeamName, tt.teamName)
			}

			if len(got.Files) != len(tt.wantFiles) {
				t.Errorf("files = %v, want %v", got.Files, tt.wantFiles)
			} else {
				for i, f := range tt.wantFiles {
					if got.Files[i] != f {
						t.Errorf("files[%d] = %q, want %q", i, got.Files[i], f)
					}
				}
			}

			if tt.wantIn != "" && !strings.Contains(got.Content, tt.wantIn) {
				t.Errorf("content missing %q, got: %s", tt.wantIn, got.Content)
			}

			if got.Size != len(got.Content) {
				t.Errorf("size = %d, want %d (len of content)", got.Size, len(got.Content))
			}

			if got.Tokens == 0 {
				t.Error("tokens = 0, want > 0")
			}
		})
	}
}

func TestIsAutoGeneratedAgentsMD(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "auto-generated with version",
			content: "# SageOx\n\n---\n*Generated by SageOx CLI v0.17.0 at 2026-01-01*\n",
			want:    true,
		},
		{
			name:    "real team instructions",
			content: "# Team Instructions\n\nUse Go.\n",
			want:    false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAutoGeneratedAgentsMD(tt.content); got != tt.want {
				t.Errorf("isAutoGeneratedAgentsMD() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCanonicalAgentType(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{name: "empty", in: "", want: ""},
		{name: "codex", in: "codex", want: "codex"},
		{name: "claude-code alias", in: "claude-code", want: "claude"},
		{name: "claude display", in: "Claude Code", want: "claude"},
		{name: "cursor display", in: "Cursor", want: "cursor"},
		{name: "already slug", in: "cursor", want: "cursor"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := canonicalAgentType(tt.in)
			if got != tt.want {
				t.Errorf("canonicalAgentType(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestCodexLifecycleNotification(t *testing.T) {
	tests := []struct {
		name      string
		agentType string
		wantEmpty bool
	}{
		{name: "codex", agentType: "codex", wantEmpty: false},
		{name: "codex display alias", agentType: "Codex", wantEmpty: false},
		{name: "claude", agentType: "claude", wantEmpty: true},
		{name: "empty", agentType: "", wantEmpty: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := codexLifecycleNotification(tt.agentType)
			if tt.wantEmpty && got != "" {
				t.Fatalf("codexLifecycleNotification(%q) = %q, want empty", tt.agentType, got)
			}
			if !tt.wantEmpty {
				if got == "" {
					t.Fatalf("codexLifecycleNotification(%q) = empty, want non-empty", tt.agentType)
				}
				if !strings.Contains(got, "hooks via .codex/hooks.json") {
					t.Errorf("expected Codex lifecycle note to mention hooks.json, got: %q", got)
				}
				if !strings.Contains(got, "ox integrate install --codex") {
					t.Errorf("expected Codex lifecycle note to mention install command, got: %q", got)
				}
			}
		})
	}
}

func TestLoadTeamMemory_ObservationGuide(t *testing.T) {
	tests := []struct {
		name      string
		setup     func(dir string) // create files under dir
		wantGuide bool
	}{
		{
			name: "GUIDE.md exists",
			setup: func(dir string) {
				memDir := filepath.Join(dir, "memory")
				os.MkdirAll(memDir, 0755)
				os.WriteFile(filepath.Join(memDir, "GUIDE.md"), []byte("# Observation Guide\n"), 0644)
			},
			wantGuide: true,
		},
		{
			name:      "GUIDE.md absent",
			setup:     func(dir string) {},
			wantGuide: false,
		},
		{
			name: "memory dir exists but no GUIDE.md",
			setup: func(dir string) {
				os.MkdirAll(filepath.Join(dir, "memory"), 0755)
			},
			wantGuide: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			tt.setup(dir)

			info := &teamContextInfo{}
			loadTeamMemory(info, dir)

			if tt.wantGuide {
				want := filepath.Join(dir, "memory", "GUIDE.md")
				if info.ObservationGuideHint != want {
					t.Errorf("ObservationGuideHint = %q, want %q", info.ObservationGuideHint, want)
				}
			} else {
				if info.ObservationGuideHint != "" {
					t.Errorf("ObservationGuideHint = %q, want empty", info.ObservationGuideHint)
				}
			}
		})
	}
}

func TestBuildGuidance_MemoryPut(t *testing.T) {
	tests := []struct {
		name       string
		teamCtx    *teamContextInfo
		featureEnv string // FEATURE_MEMORY value
		wantPut    bool
	}{
		{
			name:       "all conditions met",
			teamCtx:    &teamContextInfo{TeamID: "t", ObservationGuideHint: "/path/GUIDE.md"},
			featureEnv: "true",
			wantPut:    true,
		},
		{
			name:       "no GUIDE.md",
			teamCtx:    &teamContextInfo{TeamID: "t"},
			featureEnv: "true",
			wantPut:    false,
		},
		{
			name:       "flag off",
			teamCtx:    &teamContextInfo{TeamID: "t", ObservationGuideHint: "/path/GUIDE.md"},
			featureEnv: "",
			wantPut:    false,
		},
		{
			name:       "nil team ctx",
			teamCtx:    nil,
			featureEnv: "true",
			wantPut:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("FEATURE_MEMORY", tt.featureEnv)

			projectRoot := t.TempDir()
			g := buildGuidance("test-agent", projectRoot, tt.teamCtx, nil, "claude-code")

			found := false
			for _, cmd := range g.Commands {
				if strings.Contains(cmd.Command, "ox memory put") {
					found = true
					break
				}
			}
			if found != tt.wantPut {
				t.Errorf("ox memory put in guidance = %v, want %v", found, tt.wantPut)
			}
		})
	}
}

func TestEmitTeamMemorySection_ObservationGuide(t *testing.T) {
	tests := []struct {
		name          string
		tc            *teamContextInfo
		featureEnv    string
		wantGuide     bool // expect "GUIDE.md:" in output
		wantDirective bool // expect "Observation Recording (Active)" behavioral directive
		wantMemory    bool // expect "## Team Memory" header
		wantSoul      bool // expect "SOUL.md:" in output
	}{
		{
			name:          "GUIDE.md with flag on",
			tc:            &teamContextInfo{ObservationGuideHint: "/team/memory/GUIDE.md"},
			featureEnv:    "true",
			wantGuide:     true,
			wantDirective: true,
			wantMemory:    true,
		},
		{
			name:       "GUIDE.md with flag off",
			tc:         &teamContextInfo{ObservationGuideHint: "/team/memory/GUIDE.md"},
			featureEnv: "",
			wantGuide:  false,
			wantMemory: false,
		},
		{
			name:          "GUIDE.md and SOUL.md with flag on",
			tc:            &teamContextInfo{SoulHint: "/team/SOUL.md", ObservationGuideHint: "/team/memory/GUIDE.md"},
			featureEnv:    "true",
			wantGuide:     true,
			wantDirective: true,
			wantMemory:    true,
			wantSoul:      true,
		},
		{
			name:       "no hints at all",
			tc:         &teamContextInfo{},
			featureEnv: "true",
			wantGuide:  false,
			wantMemory: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("FEATURE_MEMORY", tt.featureEnv)

			var buf bytes.Buffer
			cmd := &cobra.Command{}
			cmd.SetOut(&buf)

			emitTeamMemorySection(cmd, tt.tc)
			out := buf.String()

			if got := strings.Contains(out, "## Team Memory"); got != tt.wantMemory {
				t.Errorf("'## Team Memory' present = %v, want %v\noutput: %s", got, tt.wantMemory, out)
			}
			if got := strings.Contains(out, "GUIDE.md:"); got != tt.wantGuide {
				t.Errorf("'GUIDE.md:' present = %v, want %v\noutput: %s", got, tt.wantGuide, out)
			}
			if got := strings.Contains(out, "Observation Recording (Active)"); got != tt.wantDirective {
				t.Errorf("'Observation Recording (Active)' present = %v, want %v\noutput: %s", got, tt.wantDirective, out)
			}
			if tt.wantDirective {
				if !strings.Contains(out, "Proactively record observations") {
					t.Errorf("expected proactive instruction in output, got: %s", out)
				}
			}
			if tt.wantSoul {
				if !strings.Contains(out, "SOUL.md:") {
					t.Errorf("expected 'SOUL.md:' in output, got: %s", out)
				}
			}
		})
	}
}
